### PR TITLE
+Dockerfile

### PR DESCRIPTION
**Pull request by schvin**
Add a simple dockerfile for arbitrary usage.

### CODE REVIEW

**Comment by flaccid** [comment]
+1 to this.

**Comment by jirutka** [comment]
-1 for this, it’s extreme overkill to run whole bloated Ubuntu in Docker just to use simple Python utility.

**Comment by mfussenegger** [comment]
If this gets included I'd at least recommend to optimize the Dockerfile a bit. 

The RUN commands to add the httpie user/group all cause extra layers which are very unlikely to be shared. See [Dockerfile best practices](https://docs.docker.com/engine/articles/dockerfile_best-practices/).
And using Ubuntu as base is probably not the best option either. There are [dedicated python images](https://hub.docker.com/_/python/). Especially python:alpine might be interesting as it would result in a much smaller image.

**Comment by schvin** [comment]
definitely agree - those images and such were not available 2 years ago when this PR was submitted, so it could definitely use some improvements ;)

given the time that has passed i assumed there was no interest. happy to clean it up and trim it down if others want it - i use it all the time and find it super useful!

**Comment by jkbrzt** [comment]
@schvin thanks but I don't think including it inside the repo adds a lot of value

**Comment by flaccid** [comment]
Work in progress: https://github.com/flaccid/docker-httpie. Happy to take contribution and will maintain it.

**Comment by hoatle** [comment]
I added this: https://github.com/teracyhq/docker-files/tree/master/httpie-jwt-auth that you can use the built Docker image right away

https://hub.docker.com/r/teracy/httpie-jwt-auth/tags/

I'm using this Docker image and it works great. I'll find a way to build official Docker image for this project with docs (as we did for https://github.com/teracyhq/docker-files/tree/master/httpie-jwt-auth)

Let me create an issue for this first.

**Comment by hoatle** [comment]
issue created: https://github.com/jakubroztocil/httpie/issues/571

**Pull request closed without merging**
