### PR TITLE
Added --pretty=unsorted support

### PR DESCRIPTION
**Pull request by kracekumar**
Pull request for issue #128. I wrote a dummy testcase that passes. Looking for feedback.

### CODE REVIEW

**Comment by lieut-data** [comment]
:+1:

**Comment by lapo-luchini** [comment]
I'd like to use this too.
What is missing for landing?
(how can I help?)

**Comment by jkbrzt** [comment]
@lapo-luchini I'm interested and working on in a more generic of configuring the formatters. This is too much of an ad-hoc solution.

**Comment by ralphschindler** [comment]
do you have a feature branch for the more generic solution?

**Comment by opensas** [comment]
I found the following workqround, instead of using httpie I found [curlie](https://curlie.io/), which seems to

> Like curl but unlike httpie, headers are written on stderr instead of stdout.

So I can use it like this:

```shell
$ curlie GET localhost:3000/tasks | jq -C
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 304
ETag: W/"130-ED1W4hQo1i7na7wy5Ewc7iKdoJc"
Date: Wed, 27 May 2020 06:28:26 GMT
Connection: keep-alive

[
  {
    "id": 2,
    "title": "new task2",
    "description": "description2",
    "status": "OPEN"
  },
  {
    "id": 3,
    "title": "new task3",
    "description": "description3",
    "status": "OPEN"
  }
]
```

Where as with httpie I would the headers

BTW, I created this convenient script:

```shell
$ cat ~/bin/c
curlie "$@" | jq -C
```

**Pull request closed without merging**
