### PR TITLE
Codestyle environment

### PR DESCRIPTION
**Pull request by medecau**
This pull-request adds a separate environ for codestyle testing.

Currently ignores E241 and E501 errors.

I also fixed some code style errors.

### CODE REVIEW

**Comment by medecau** [comment]
I did not include travis changes as I'm afraid I'll mess up the file.

**Comment by medecau** [comment]
It took me a few tries but I was able to config travis to run an independent environment for pycodestyle.

I wanted to point the python version to the value in NEWEST_PYTHON but gave up on that.
https://github.com/medecau/httpie/blob/e11cc312b8037890af21d3361760783d4c02ba67/.travis.yml#L50

pinging @jkbrzt @msabramo for review

**Comment by msabramo** [comment]
👍 
Nice work, @medecau!

**Comment by jkbrzt** [comment]
Obrigado, @medecau!

**Comment by medecau** [comment]
-.-'

De nada!

**Pull request merged**
