### PR TITLE
Base URL feature

### PR DESCRIPTION
**Pull request by nrocco**
See for an explanation of the feature (and the use case for it) in issue #215

I, on purpose, implemented the feature separately from the curl shorthand syntax.
The only thing missing in the Pull Request is tests.

### CODE REVIEW

**Comment by nrocco** [comment]
Hi @jakubroztocil 
Have you had the time to look at my PR which introduces the `BASE_URL` feature?
Does it still fit the vision of `httpie`?

**Comment by nrocco** [comment]
Hi @jakubroztocil just checking in to see if this is still on the roadmap.

**Comment by grimborg** [comment]
I'm also interested in seeing this feature live.

**Comment by heydonovan** [comment]
+1

**Comment by knxroot** [comment]
+1

**Comment by nrocco** [comment]
Hi @jakubroztocil,

I added unit tests to the pull request. I'd love to see this merged. Is there anything I can help with or need to change for that to happen?

Thanks.

**Comment by nrocco** [comment]
@jkbrzt Will this ever get merged in?

**Comment by jkbrzt** [comment]
@nrocco thanks for for the pull request! I think this should be a job for an external wrapper around HTTPie. Have a look at https://github.com/eliangcs/http-prompt which does an amazing job.

**Comment by noahcoad** [comment]
+1 for this HTTPIE_BASE_URL feature request

**Comment by Morantron** [comment]
First of all, I want to say this is an amazing tool!

I think you should reconsider adding this feature @jakubroztocil 

Main use case is containers being used more and more for local development, so just having `localhost` isn't enough.

A tool like `http-prompt` doesn't fit my workflow because I use a vim+tmux to interact with REPLs. While this approach is kind of niche, the `HTTPIE_BASEURL` env vars would be a perfectly fine solution. The implementation doesn't seem to add much complexity, and would allow more ways to enjoy httpie.

**Comment by qiulang** [comment]
Hi, I still don't know how to use Base URL in desktop app.  https://httpie.io/docs/desktop/relative-urls says,

> Besides complete URLs, HTTPie also makes relative ones (like /api/users) interactive by prefixing the request’s base URL.

But how do I do that exactly ? Can someone shed some light ?

**Pull request closed without merging**
